import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ParticlesBackground from "@/components/ParticlesBackground";
import { ThemeProvider } from "@/context/ThemeContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
        <div className="min-h-screen bg-gradient-to-br from-gray-900 via-black to-gray-800 text-white">
        <ParticlesBackground />
        {children}
        </div>
        <script src="/scripts/script.js"></script>
        </ThemeProvider>
      </body>
    </html>
  );
}
