name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or change to 'dev' or whichever branch you want to trigger deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: portfolio

      - name: Build the project
        run: npm run build
        working-directory: portfolio

      - name: Export static site
        run: npm run export
        working-directory: portfolio

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: portfolio/out
